[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Change partition table to expand application space to 3MB
board_build.partitions = huge_app.csv

; Serial Monitor Speed
monitor_speed = 115200

; Library Dependencies (Auto-downloaded by PlatformIO)
lib_deps =
    bblanchon/ArduinoJson
    arkhipenko/TaskScheduler
    me-no-dev/AsyncTCP
    Keypad
    olikraus/U8g2@^2.35.8

; Compiler Flags for Subfolder Includes
build_flags = 
    -I src
    -I src/Input
    -I src/UI
    -I src/Radio